import { test, expect } from '@playwright/test'

test('keyboard-confirmed demo reset clears every collection and permits a fresh empty-mode workflow',async({page})=>{
  await page.clock.install({time:new Date('2026-09-23T12:00:00Z')})
  const downloads=[]
  page.on('download',download=>downloads.push(download))
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await page.getByLabel('Data da agenda').fill('2026-10-05')
  await page.getByRole('button',{name:'Dia',exact:true}).click()
  await page.getByRole('button',{name:/14:30–15:20 · Luna Martins/}).click()
  const edit=page.getByRole('dialog',{name:'Alterar compromisso'})
  await edit.getByLabel('Aplicar a').selectOption('Cancelar ocorrência')
  await edit.getByLabel('Motivo do cancelamento').fill('Cancelamento sintético para limpeza')
  await edit.getByRole('button',{name:'Confirmar cancelamento'}).click()
  await expect(page.getByRole('region',{name:'Histórico de alterações da agenda'})).toContainText('Cancelamento sintético para limpeza')
  await page.getByRole('navigation').getByRole('button',{name:'Pacientes'}).click()
  await page.getByRole('button',{name:/Theo Almeida/}).click()
  await page.getByRole('button',{name:/Iniciar sessão/}).click()
  await page.getByLabel('Como o paciente chegou?').fill('Rascunho sintético antes da limpeza')
  await page.getByRole('button',{name:'Guardar rascunho nesta sessão'}).click()
  await page.getByRole('navigation').getByRole('button',{name:'Ajustes'}).click()
  const exit=page.getByRole('dialog',{name:'Sair da sessão?'})
  if(await exit.isVisible())await exit.getByRole('button',{name:/Sair mantendo rascunho/}).click()
  const counts=page.getByRole('region',{name:'Resumo dos registros temporários'})
  for(const value of ['Perfis: 4','Séries: 1','Exceções individuais: 1','Sessões finalizadas: 1','Itens da biblioteca: 6','Rascunhos: 1'])await expect(counts).toContainText(value)
  const before=await counts.innerText()
  const trigger=page.getByRole('button',{name:'Limpar demonstração'})
  await trigger.focus()
  await trigger.press('Enter')
  const dialog=page.getByRole('alertdialog',{name:'Limpar a demonstração?'})
  await expect(dialog).toHaveAttribute('aria-modal','true')
  await expect(dialog.getByRole('button',{name:'Cancelar'})).toBeFocused()
  await expect(page.locator('nav')).toHaveAttribute('inert','')
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button',{name:'Fechar Limpar a demonstração?'})).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button',{name:'Cancelar'})).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  expect(await counts.innerText()).toBe(before)
  await trigger.press('Enter')
  await dialog.getByRole('button',{name:'Cancelar'}).press('Enter')
  await expect(dialog).toHaveCount(0)
  expect(await counts.innerText()).toBe(before)
  await trigger.press('Enter')
  await expect(dialog).toContainText('nem cria backup')
  await dialog.getByRole('button',{name:'Confirmar limpeza'}).focus()
  await page.keyboard.press('Enter')
  await expect(dialog).toHaveCount(0)
  await expect(counts.getByRole('heading',{name:'Registros temporários nesta sessão'})).toBeFocused()
  for(const value of ['Perfis: 0','Séries: 0','Exceções individuais: 0','Mudanças de série: 0','Sessões finalizadas: 0','Itens da biblioteca: 0','Rascunhos: 0'])await expect(counts).toContainText(value)
  await expect(trigger).toBeDisabled()
  await expect(page.locator('nav')).not.toHaveAttribute('inert','')
  await expect(page.getByRole('navigation').getByRole('button',{name:'Perfil'})).toBeDisabled()
  expect(downloads).toHaveLength(0)

  await page.getByRole('navigation').getByRole('button',{name:'Pacientes'}).click()
  await expect(page.getByText(/Nenhum perfil cadastrado/)).toBeVisible()
  await expect(page.locator('.kid-card')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'Biblioteca'}).click()
  await expect(page.getByText(/Nenhum item na biblioteca/)).toBeVisible()
  await expect(page.locator('.library-row')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await expect(page.getByText(/Cadastre um perfil fictício/)).toBeVisible()
  await expect(page.getByRole('button',{name:/Novo compromisso recorrente/})).toBeDisabled()
  await expect(page.getByRole('region',{name:'Notas administrativas das séries da agenda'})).toContainText('Nenhuma série registrada')
  await expect(page.getByRole('region',{name:'Histórico de alterações da agenda'})).toContainText('Nenhuma alteração registrada')

  await page.getByRole('navigation').getByRole('button',{name:'Pacientes'}).click()
  await page.getByRole('button',{name:/Cadastrar paciente/}).click()
  await page.getByLabel('Nome',{exact:true}).fill('Recomeço Sintético')
  await page.getByLabel('Ciclo de vida').selectOption('Adulto')
  await page.getByRole('button',{name:'Salvar paciente'}).click()
  await expect(page.getByRole('heading',{name:'Recomeço Sintético'})).toBeVisible()
  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await page.getByLabel('Data da agenda').fill('2026-10-06')
  await page.getByRole('button',{name:/Novo compromisso recorrente/}).click()
  const create=page.getByRole('dialog',{name:'Nova série recorrente'})
  await expect(create.getByLabel('Paciente')).toHaveValue(/.+/)
  await create.getByRole('button',{name:'Criar série'}).click()
  await page.getByRole('button',{name:'Dia',exact:true}).click()
  await expect(page.getByRole('button',{name:/09:00–09:50 · Recomeço Sintético/})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button',{name:/Luna Martins/})).toBeVisible()
  await expect(page.getByRole('button',{name:/Recomeço Sintético/})).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'Ajustes'}).click()
  await expect(page.getByRole('region',{name:'Resumo dos registros temporários'})).toContainText('Perfis: 4')
  expect(downloads).toHaveLength(0)
})
