import { test, expect } from '@playwright/test'

test('synthetic patient journey keeps agenda, draft, session snapshot and next occurrence consistent',async({page})=>{
  await page.clock.install({time:new Date('2026-09-23T12:00:00Z')})
  await page.goto('/')
  const addPatient=async(name,lifeCycle,modality)=>{
    await page.getByRole('button',{name:/Cadastrar paciente/}).click()
    await page.getByLabel('Nome',{exact:true}).fill(name)
    await page.getByLabel('Ciclo de vida').selectOption(lifeCycle)
    await page.getByLabel('Modalidade preferida (opcional)').selectOption(modality)
    await page.getByRole('button',{name:'Salvar paciente'}).click()
    await page.getByRole('button',{name:/Voltar aos pacientes/}).click()
    const card=page.getByRole('button',{name:new RegExp(name)})
    const id=(await card.getAttribute('aria-label')).match(/ID ([^ ]+)/)?.[1]
    expect(id).toBeTruthy()
    return id
  }
  const childId=await addPatient('Helena Jornada','Criança','Online')
  const adultId=await addPatient('Rafael Jornada','Adulto','Presencial')
  expect(childId).not.toBe(adultId)

  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await page.getByLabel('Data da agenda').fill('2026-10-06')
  await page.getByRole('button',{name:/Novo compromisso recorrente/}).click()
  const create=page.getByRole('dialog',{name:'Nova série recorrente'})
  await create.getByLabel('Paciente').selectOption({label:'Helena Jornada'})
  await expect(create.getByLabel('Modalidade')).toHaveValue('Online')
  const link='https://example.test/sala-helena-jornada'
  await create.getByLabel('Link externo da série (opcional)').fill(link)
  await create.getByRole('button',{name:'Criar série'}).click()
  await page.getByRole('button',{name:'Dia',exact:true}).click()
  await page.getByRole('button',{name:/09:00–09:50 · Helena Jornada/}).click()
  const appointment=page.getByRole('dialog',{name:'Alterar compromisso'})
  const target=await appointment.getByRole('group',{name:'Compromisso selecionado'}).innerText()
  const seriesId=target.match(/Série ([^\s]+)/)?.[1]
  expect(target).toContain(`ID ${childId}`)
  expect(seriesId).toBeTruthy()
  await appointment.getByRole('button',{name:'Iniciar sessão'}).click()
  await expect(page.getByLabel('Data',{exact:true})).toHaveValue('2026-10-06')
  await expect(page.getByLabel('Modalidade')).toHaveValue('Online')
  await expect(page.getByLabel('Link externo (opcional)')).toHaveValue(link)
  await page.getByRole('button',{name:/Continuar/}).click()
  await page.getByRole('button',{name:'Selecionar emoção Calma'}).click()
  await page.getByRole('button',{name:/Continuar/}).click()
  await page.getByLabel('Buscar comportamento ativo na biblioteca').fill('Evitar atividade')
  await page.getByRole('button',{name:/Evitar atividade.*Engajamento/}).click()
  await expect(page.getByRole('button',{name:/Remover Evitar atividade deste rascunho/})).toBeVisible()
  await page.getByRole('button',{name:/Continuar/}).click()
  const regulation=page.locator('.ind-card').filter({has:page.getByRole('heading',{name:'Regulação emocional'})})
  await regulation.getByRole('button',{name:/Ainda não observado/}).click()
  await expect(regulation.getByRole('status')).toContainText('Ainda não observado')
  const communication=page.locator('.ind-card').filter({has:page.getByRole('heading',{name:'Comunicação de necessidades'})})
  await expect(communication.getByRole('status')).toContainText('Sem registro')
  await page.getByRole('button',{name:/Continuar/}).click()
  const summary='Resumo sintético da jornada Helena',privateNote='Nota privada sintética da jornada Helena'
  await page.getByLabel('Resumo da sessão').fill(summary)
  await page.getByLabel('Anotação privada').fill(privateNote)
  await page.getByRole('button',{name:'Guardar rascunho nesta sessão'}).click()
  await page.getByRole('navigation').getByRole('button',{name:'Pacientes'}).click()
  const exit=page.getByRole('dialog',{name:'Sair da sessão?'})
  if(await exit.isVisible())await exit.getByRole('button',{name:/Sair mantendo rascunho/}).click()
  await page.getByRole('button',{name:/Helena Jornada/}).click()
  await page.getByRole('button',{name:/Iniciar sessão/}).click()
  await expect(page.getByLabel('Link externo (opcional)')).toHaveValue(link)
  for(let step=0;step<3;step++)await page.getByRole('button',{name:/Continuar/}).click()
  await expect(regulation.getByRole('button',{name:/Ainda não observado/})).toHaveAttribute('aria-pressed','true')
  await expect(communication.getByRole('status')).toContainText('Sem registro')
  await page.getByRole('button',{name:/Continuar/}).click()
  await expect(page.getByLabel('Resumo da sessão')).toHaveValue(summary)
  await expect(page.getByLabel('Anotação privada')).toHaveValue(privateNote)
  let confirmation=''
  page.once('dialog',async dialog=>{confirmation=dialog.message();await dialog.accept()})
  await page.getByRole('button',{name:'Finalizar sessão'}).click()
  expect(confirmation).toContain(`Helena Jornada (ID ${childId})`)
  for(const text of [summary,privateNote,link])expect(confirmation).not.toContain(text)
  const record=page.locator('.record').filter({hasText:summary})
  await expect(record).toHaveCount(1)
  await expect(record).toContainText(link)
  await expect(record.getByRole('group',{name:'Origem da agenda'})).toContainText(`Série ${seriesId} · Original: 2026-10-06 · Efetiva: 2026-10-06`)
  await expect(record.getByRole('region',{name:'Comportamentos registrados'})).toContainText('Evitar atividade')
  await expect(page.locator('main')).not.toContainText(privateNote)
  const indicatorSummary=page.getByRole('region',{name:'Indicadores da sessão mais recente'})
  await expect(indicatorSummary).toContainText('Ainda não observado')
  await expect(indicatorSummary).toContainText('Sem registro')
  await page.getByRole('button',{name:/Ver evolução/}).first().click()
  await expect(page.getByRole('heading',{name:'Helena Jornada'})).toBeVisible()
  await expect(page.getByRole('article',{name:'Regulação emocional'})).toContainText('0 / 3')
  await expect(page.getByRole('article',{name:'Comunicação de necessidades'})).toContainText('Sem posição registrada')
  await expect(page.locator('main')).not.toContainText(privateNote)
  await page.getByRole('button',{name:/Voltar ao perfil/}).click()
  await page.getByRole('button',{name:/Voltar aos pacientes/}).click()
  await page.getByRole('button',{name:/Rafael Jornada/}).click()
  await expect(page.locator('main')).not.toContainText(summary)
  await expect(page.locator('main')).not.toContainText(link)

  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await page.getByLabel('Data da agenda').fill('2026-10-13')
  await page.getByRole('button',{name:'Dia',exact:true}).click()
  await page.getByRole('button',{name:/09:00–09:50 · Helena Jornada/}).click()
  const next=page.getByRole('dialog',{name:'Alterar compromisso'})
  await expect(next.getByRole('group',{name:'Compromisso selecionado'})).toContainText(`Série ${seriesId} · ocorrência original 2026-10-13`)
  await next.getByLabel('Aplicar a').selectOption('Cancelar ocorrência')
  await next.getByLabel('Motivo do cancelamento').fill('Ajuste administrativo sintético')
  await next.getByRole('button',{name:'Confirmar cancelamento'}).click()
  await expect(page.getByRole('button',{name:/09:00–09:50 · Helena Jornada/})).toHaveCount(0)
  await expect(page.getByRole('region',{name:'Histórico de alterações da agenda'})).toContainText('Ajuste administrativo sintético')
  await page.getByRole('navigation').getByRole('button',{name:'Pacientes'}).click()
  await expect(page.getByRole('button',{name:/Helena Jornada/})).toContainText('20 de out. · 09:00')
  await page.getByRole('button',{name:/Helena Jornada/}).click()
  await expect(page.locator('.record').filter({hasText:summary})).toHaveCount(1)
  await expect(page.locator('main')).not.toContainText('Ajuste administrativo sintético')
})
