import { test, expect } from '@playwright/test'

test('patient form focuses invalid fields, keeps other values and submits once by keyboard',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:/Cadastrar paciente/}).click()
  const name=page.getByLabel('Nome',{exact:true})
  const age=page.getByLabel('Idade',{exact:true})
  const lifeCycle=page.getByLabel('Ciclo de vida')
  const modality=page.getByLabel('Modalidade preferida (opcional)')
  const save=page.getByRole('button',{name:'Salvar paciente'})
  await age.fill('7')
  await lifeCycle.selectOption('Criança')
  await modality.selectOption('Online')
  await save.focus()
  await save.press('Enter')
  await expect(page.getByRole('alert')).toContainText('nome')
  await expect(name).toBeFocused()
  await expect(name).toHaveAttribute('aria-invalid','true')
  await expect(name).toHaveAttribute('aria-describedby','patient-form-error')
  await expect(age).toHaveValue('7')
  await expect(modality).toHaveValue('Online')
  await name.fill('Paciente Sintético Foco')
  await age.fill('-1')
  await save.focus()
  await save.press('Enter')
  await expect(page.getByRole('alert')).toContainText('idade')
  await expect(age).toBeFocused()
  await expect(age).toHaveAttribute('aria-invalid','true')
  await expect(age).toHaveAttribute('aria-describedby','patient-form-error')
  await expect(name).toHaveValue('Paciente Sintético Foco')
  await expect(modality).toHaveValue('Online')
  await age.fill('7')
  await save.focus()
  await save.press('Enter')
  await expect(page.getByRole('heading',{name:'Paciente Sintético Foco'})).toBeVisible()
  await page.getByRole('button',{name:/Voltar aos pacientes/}).click()
  await expect(page.getByRole('button',{name:/Paciente Sintético Foco/})).toHaveCount(1)
})
