import { test, expect } from '@playwright/test'

test('child to adult profile edit preserves a new patient ID, series and saved draft without rewriting their choices',async({page})=>{
  await page.clock.install({time:new Date('2026-09-23T12:00:00Z')})
  await page.goto('/')
  await page.getByRole('button',{name:/Cadastrar paciente/}).click()
  await page.getByLabel('Nome',{exact:true}).fill('Bia Ciclo Sintético')
  await page.getByLabel('Ciclo de vida').selectOption('Criança')
  await page.getByLabel('Modalidade preferida (opcional)').selectOption('Online')
  await page.getByRole('button',{name:'Salvar paciente'}).click()
  await expect(page.getByRole('heading',{name:'Bia Ciclo Sintético'})).toBeVisible()
  await expect(page.locator('.record')).toHaveCount(0)
  await page.getByRole('button',{name:/Voltar aos pacientes/}).click()
  const initialCard=page.getByRole('button',{name:/Bia Ciclo Sintético/})
  const patientId=(await initialCard.getAttribute('aria-label')).match(/ID ([^ ]+)/)?.[1]
  expect(patientId).toBeTruthy()

  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await page.getByLabel('Data da agenda').fill('2026-09-29')
  await page.getByRole('button',{name:/Novo compromisso recorrente/}).click()
  const create=page.getByRole('dialog',{name:'Nova série recorrente'})
  await create.getByLabel('Paciente').selectOption({label:'Bia Ciclo Sintético'})
  await expect(create.getByLabel('Modalidade')).toHaveValue('Online')
  const link='https://example.test/sala-bia-ciclo'
  await create.getByLabel('Link externo da série (opcional)').fill(link)
  await create.getByRole('button',{name:'Criar série'}).click()
  await page.getByRole('button',{name:'Dia',exact:true}).click()
  await page.getByRole('button',{name:/09:00–09:50 · Bia Ciclo Sintético/}).click()
  const appointment=page.getByRole('dialog',{name:'Alterar compromisso'})
  const target=await appointment.getByRole('group',{name:'Compromisso selecionado'}).innerText()
  const seriesId=target.match(/Série ([^\s]+)/)?.[1]
  expect(target).toContain(`ID ${patientId}`)
  expect(seriesId).toBeTruthy()
  await appointment.getByRole('button',{name:'Iniciar sessão'}).click()
  await expect(page.getByLabel('Modalidade')).toHaveValue('Online')
  await expect(page.getByLabel('Link externo (opcional)')).toHaveValue(link)
  await page.getByLabel('Como o paciente chegou?').fill('Chegada sintética preservada no rascunho')
  await page.getByRole('button',{name:'Guardar rascunho nesta sessão'}).click()
  await page.getByRole('navigation').getByRole('button',{name:'Perfil'}).click()
  const exit=page.getByRole('dialog',{name:'Sair da sessão?'})
  if(await exit.isVisible())await exit.getByRole('button',{name:/Sair mantendo rascunho/}).click()
  await expect(page.locator('.record')).toHaveCount(0)
  await page.getByRole('button',{name:'Editar perfil'}).click()
  const edit=page.getByRole('dialog',{name:'Editar dados do paciente'})
  await expect(edit.getByLabel('Status')).toHaveCount(0)
  await edit.getByLabel('Nome').fill('Bia Adulta Sintética')
  await edit.getByLabel('Ciclo de vida').selectOption('Adulto')
  await edit.getByLabel('Modalidade preferida (opcional)').selectOption('Presencial')
  await edit.getByRole('button',{name:'Salvar alterações'}).click()
  await expect(page.getByRole('heading',{name:'Bia Adulta Sintética'})).toBeVisible()
  await expect(page.getByText(/Adulto ·/)).toBeVisible()
  await expect(page.locator('.record')).toHaveCount(0)
  await page.getByRole('button',{name:/Voltar aos pacientes/}).click()
  const updatedCard=page.getByRole('button',{name:/Bia Adulta Sintética/})
  await expect(updatedCard).toHaveAccessibleName(new RegExp(`ID ${patientId}`))
  await expect(updatedCard).toContainText('Em acompanhamento')
  await expect(page.getByRole('button',{name:/Bia Ciclo Sintético/})).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'Agenda'}).click()
  await page.getByLabel('Data da agenda').fill('2026-09-29')
  await page.getByRole('button',{name:'Dia',exact:true}).click()
  const occurrence=page.getByRole('button',{name:/09:00–09:50 · Bia Adulta Sintética/})
  await expect(occurrence).toHaveAccessibleName(new RegExp(`ID ${patientId}`))
  await expect(occurrence).toContainText('Online')
  await occurrence.click()
  await expect(page.getByRole('dialog',{name:'Alterar compromisso'}).getByRole('group',{name:'Compromisso selecionado'})).toContainText(`Série ${seriesId}`)
  await page.getByRole('dialog',{name:'Alterar compromisso'}).getByRole('button',{name:'Iniciar sessão'}).click()
  await expect(page.getByLabel('Como o paciente chegou?')).toHaveValue('Chegada sintética preservada no rascunho')
  await expect(page.getByLabel('Modalidade')).toHaveValue('Online')
  await expect(page.getByLabel('Link externo (opcional)')).toHaveValue(link)
  await page.getByRole('button',{name:/Continuar/}).click()
  await expect(page.getByText(/Registro emocional · confirmação do profissional/i)).toBeVisible()
  await expect(page.getByText(/Modo visual infantil/i)).toHaveCount(0)
})
